name: DeathSwap
version: 1.0.0
main: steffanvanderwerf.deathswap.Deathswap
api-version: 1.19
authors: [ steffanvanderwerf ]
commands:
    players:
        description: Set player1 and player2
        usage: /players [set|get] <player1> <player2>
        permission: players.set
    deathswap:
        description: DeathSwap command
        usage: /<command> [start|stop] [swapTime]
        aliases: [ ds ]
        permission: deathswap.start